# Generated by Django 4.2.3 on 2023-07-25 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_freelancer_profile_picture_user_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
    ]
