# Generated by Django 4.2.3 on 2023-07-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterModelTable(
            name='client',
            table='client',
        ),
    ]
